### ISSUE TITLE
Add basic Quiz api

### ISSUE THREAD

**Issue by Shushunya** [Shushunya/quizzy#2]
### Tasks

`urls.py`
- [x] add `quizzes` url
- [x] add `questions` url
- [x] add `answers` url

`serializers.py`
- [x] add quiz serializer
- [x] add question serializer
- [x] add answer serializer

`views.py`
- [x] add quiz view
- [x] add question view
- [x] add answer view

### DoR

- [x] all serializer tests from #8 pass
- [x] all api tests from #8 pass
