### ISSUE TITLE
test models v0.0

### ISSUE THREAD

**Issue by Shushunya** [Shushunya/quizzy#20]
**Subtask of** #8 

- [x] all models [`Quiz`, `Question`, `Answer`] object creation
- [x] all models string representation
- [x] `Quiz` model plural verbose name
